name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specifica la versione di Node.js da utilizzare

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Build
      run: |
        npm run build  # Specifica il comando di build

    - name: Publish package
      if: startsWith(github.ref, 'refs/tags/')  # Pubblica solo sui tag delle versioni
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Usa un segreto per l'autenticazione
